services:
  eureka-service:
    image: eureka-service
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eureka-service
    environment:
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
    ports:
      - "8761:8761"
    networks:
      - app-network

  config-service:
    image: config-service
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config-service
    volumes:
      - ./config-service/configurations:/configurations 
    environment:
      - SPRING_PROFILES_ACTIVE=native
    ports:
      - "8888:8888"
    networks:
      - app-network


  usuario-service:
    image: usuario-service
    build:
      context: ./usuario-service  
      dockerfile: Dockerfile
    container_name: usuario-service
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/miup_bd
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka
    ports:
      - "8090:8090"  
    depends_on:
      - eureka-service
      - config-service
    networks:
      - app-network

  product-service:
    image: product-service
    build:
      context: ./product-service  
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/miup_bd
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka
    ports:
      - "8092:8092"  
    depends_on:
      - eureka-service
      - config-service
    networks:
      - app-network

  auth-service:
    image: auth-service
    build:
      context: ./auth-service 
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka
    ports:
      - "8089:8089"  
    depends_on:
      - eureka-service
      - config-service
      - usuario-service
    networks:
      - app-network

  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway  
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=native
    ports:
      - "9191:9191"
    depends_on:
      - eureka-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
