services:
  # Eureka service (Service Discovery)
  eureka-service:
    image: eureka-service
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eureka-service
    environment:
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
    ports:
      - "8761:8761"
    networks:
      - app-network

  # Config service (si no tienes uno dockerizado, usaremos un servicio de ejemplo)
  config-service:
    image: config-service
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config-service
    volumes:
      - ./config-service/configurations:/configurations # Monta los archivos en el contenedor
    environment:
      - SPRING_PROFILES_ACTIVE=native
    ports:
      - "8888:8888"
    networks:
      - app-network

  # Microservicios (reemplaza con el nombre de tus servicios)
  usuario-service:
    image: usuario-service
    build:
      context: ./usuario-service  # Ruta a tu microservicio 1
      dockerfile: Dockerfile
    container_name: usuario-service
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_DATASOURCE_URL=jdbc:mysql://miup-sistema-gestion.cvuqusmy082l.us-east-2.rds.amazonaws.com:3306/miup_bd
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=Frank888RGMiupSG
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka
    ports:
      - "8090:8090"  # Ajusta el puerto según sea necesario
    depends_on:
      - eureka-service
      - config-service
    networks:
      - app-network

  product-service:
    image: product-service
    build:
      context: ./product-service  # Ruta a tu microservicio 2
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_DATASOURCE_URL=jdbc:mysql://miup-sistema-gestion.cvuqusmy082l.us-east-2.rds.amazonaws.com:3306/miup_bd
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=Frank888RGMiupSG
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka
    ports:
      - "8092:8092"  # Ajusta el puerto según sea necesario
    depends_on:
      - eureka-service
      - config-service
    networks:
      - app-network

  auth-service:
    image: auth-service
    build:
      context: ./auth-service  # Ruta a tu microservicio 3
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka
    ports:
      - "8089:8089"  # Ajusta el puerto según sea necesario
    depends_on:
      - eureka-service
      - config-service
      - usuario-service
    networks:
      - app-network

  # Agrega aquí los otros microservicios de manera similar (microservice3, microservice4, microservice5)


  # API Gateway (si es un microservicio independiente)
  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway  # Ruta a tu API Gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=native
    ports:
      - "9191:9191"
    depends_on:
      - eureka-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
