server:
  port: 8089

spring:
  application:
    name: auth-service
  
## CONFIGURACION EUREKA SERVICE --------------
eureka:
  instance: 
    hostname: localhost
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka