server:
  port: 8092

spring:
  application:
    name: product-service
  datasource:
    #url: jdbc:mysql://localhost:3306/miup_bd?useSSL=false&serverTimezone=UTC
    #username: root
    #password: Frank800
    url: jdbc:mysql://miup-sistema-gestion.cvuqusmy082l.us-east-2.rds.amazonaws.com:3306/miup_bd?useSSL=false&serverTimezone=UTC
    username: admin
    password: Frank888RGMiupSG
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

eureka:
  client: 
    service-url:
      defaultZone: http://eureka-service:8761/eureka