server:
  port: 8092

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miup_bd
    username: root
    password: Frank800

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

eureka:
  enabled: true
  instance: 
    hostname: localhost
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka