server:
  port: 8090

spring:
  application:
    name: usuario-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/miup_bd
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Frank800

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

## CONFIGURACION EUREKA SERVICE --------------
eureka:
  instance: 
    hostname: localhost
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka